version: "3"

services:
  namenode:
    build: ./namenode
    image: tomer23/europe-gis:hadoop_namenode
    container_name: namenode
    networks:
      - hbase
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop_master.env
    ports:
      - "9870:9870"
  
  resourcemanager:
    build: ./resourcemanager
    image: tomer23/europe-gis:hadoop_resourcemanager
    container_name: resourcemanager
    networks:
      - hbase
    restart: on-failure
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop_master.env
    ports:
      - "8088:8088"
  
  historyserver:
    build: ./historyserver
    image: tomer23/europe-gis:hadoop_historyserver
    container_name: historyserver
    networks:
      - hbase
    depends_on:
      - namenode
      - datanode
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop_master.env
    ports:
      - "8188:8188"
  
  nodemanager:
    build: ./nodemanager
    image: tomer23/europe-gis:hadoop_nodemanager
    container_name: nodemanager
    networks:
      - hbase
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop_master.env
    ports:
      - "8042:8042"
  
  datanode:
    build: ./datanode
    image: tomer23/europe-gis:hadoop_datanode
    container_name: datanode
    networks:
      - hbase
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop_master.env
  

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

networks:
  hbase:
    external:
      name: hbase